create table if not exists public.mvp_items (
  id bigint generated by default as identity primary key,
  text text not null,
  created_at timestamptz not null default now()
);

alter table public.mvp_items enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'mvp_items'
      and policyname = 'mvp_items_select_anon'
  ) then
    create policy mvp_items_select_anon
      on public.mvp_items
      for select
      to anon
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'mvp_items'
      and policyname = 'mvp_items_insert_anon'
  ) then
    create policy mvp_items_insert_anon
      on public.mvp_items
      for insert
      to anon
      with check (true);
  end if;
end $$;
